version: '3'
## 遇到容器不停重启，首先怀疑是挂载目录读写执行权限问题
services:
  #### nginx ####
  #dist目录下的全部解压到/usr/local/volumes/nginx/html/
  nginx:
    image: nginx:1.22
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /usr/local/volumes/nginx/conf.d:/etc/nginx/conf.d
      - /usr/local/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/volumes/nginx/html:/usr/share/nginx/html
    environment:
      - TZ=Asia/Shanghai